name: Cypress Tests

on:
  pull_request:

env:
  SPEC1: true
  SPEC2: true
  SPEC3: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Cypress Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          sync-labels: ''
      #- name: Install Dependencies
      #  uses: cypress-io/github-action@v5
      #  with:
      #    runTests: false
      #    build: npm run build
      - name: Get Labels
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          echo "$labels"
        env:
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      - name: Build Spec Path
        uses: actions/github-script@v6
        id: spec
        with:
          result-encoding: string
          script: |
            console.log(context.issue)
            return "cypress/e2e/spec2.cy.js"
      - name: Echo Spec
        run: echo "${{steps.spec.outputs.result}}"
      - name: Echo Labels
        run: echo "$labels"

      #- name: Run E2E Tests
      #  uses: cypress-io/github-action@v5
      #  with:
      #    install: false
      #    start: npm run start
      #    wait-on: 'http://localhost:3000'
      #    browser: chrome
      #    spec: ${{steps.spec.outputs.result}}


  