name: Cypress Tests

on:
  push:

env:
  SPEC1: true
  SPEC2: true
  SPEC3: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome


  