name: Cypress Tests

on:
  push:

env:
  SPEC1: true
  SPEC2: true
  SPEC3: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: |
            ./build
  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    name: Cypress Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm run ci:start
          wait-on: 'http://localhost:3000'
          browser: chrome


  