name: Cypress Tests

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Cypress Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GitHub Context
        env: 
          GITHUB_CONTEXT: $${{toJson(github)}}
        run: |
          echo "$GITHUB_CONTEXT"
          