name: Cypress Tests

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Cypress Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GitHub Context
        env: 
          GITHUB_CONTEXT: $${{toJson(github)}}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Print SHA
        run: |
          echo ${{github.sha}}
      - name: GET PR From SHA
        id: pr_number
        run: |
          gh pr list --search ${{github.sha}} --json number
      - name: PRINT PR NUM
        run: |
          echo ${{steps.pr_number.outputs.result}}
